package com.richardjiang880.lernchih.repository;

import com.richardjiang880.lernchih.AbstractIntegrationTest;
import com.richardjiang880.lernchih.model.Channel;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;

import static org.assertj.core.api.Assertions.assertThat;

class ChannelRepositoryTest extends AbstractIntegrationTest {

    @Autowired
    private ChannelRepository channelRepository;

    @BeforeEach
    void cleanUp() {
        channelRepository.deleteAll();
    }

    @Test
    void findBySlugReturnsChannelWhenExists() {
        Channel channel = Channel.builder()
                .name("Java")
                .slug("java")
                .description("Java discussions")
                .build();
        channelRepository.save(channel);

        assertThat(channelRepository.findBySlug("java"))
                .isPresent()
                .hasValueSatisfying(c -> assertThat(c.getName()).isEqualTo("Java"));
    }

    @Test
    void findBySlugReturnsEmptyWhenNotExists() {
        assertThat(channelRepository.findBySlug("missing")).isEmpty();
    }

    @Test
    void existsBySlugReturnsTrueForExistingSlug() {
        Channel channel = Channel.builder()
                .name("Spring Boot")
                .slug("spring-boot")
                .build();
        channelRepository.save(channel);

        assertThat(channelRepository.existsBySlug("spring-boot")).isTrue();
    }

    @Test
    void existsBySlugReturnsFalseForUnknownSlug() {
        assertThat(channelRepository.existsBySlug("unknown")).isFalse();
    }

    @Test
    void slugIsAutoGeneratedFromNameWhenNotProvided() {
        Channel channel = Channel.builder()
                .name("Test Channel")
                .build();
        Channel saved = channelRepository.save(channel);

        assertThat(saved.getSlug()).isEqualTo("test-channel");
    }
}
