package com.richardjiang880.lernchih.repository;

import com.richardjiang880.lernchih.AbstractRepositoryTest;
import com.richardjiang880.lernchih.model.Channel;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.jpa.test.autoconfigure.TestEntityManager;

import static org.assertj.core.api.Assertions.assertThat;

class ChannelRepositoryJpaTest extends AbstractRepositoryTest {

    @Autowired
    private ChannelRepository channelRepository;

    @Autowired
    private TestEntityManager entityManager;

    @Test
    void findBySlugReturnsChannelWhenExists() {
        persistChannel("java", "Java");

        assertThat(channelRepository.findBySlug("java"))
                .isPresent()
                .hasValueSatisfying(c -> assertThat(c.getName()).isEqualTo("Java"));
    }

    @Test
    void findBySlugReturnsEmptyWhenNotExists() {
        assertThat(channelRepository.findBySlug("missing")).isEmpty();
    }

    @Test
    void existsBySlugReturnsTrueForExistingSlug() {
        persistChannel("spring-boot", "Spring Boot");

        assertThat(channelRepository.existsBySlug("spring-boot")).isTrue();
    }

    @Test
    void existsBySlugReturnsFalseForUnknownSlug() {
        assertThat(channelRepository.existsBySlug("unknown")).isFalse();
    }

    @Test
    void slugIsAutoGeneratedFromNameWhenNotProvided() {
        Channel channel = Channel.builder().name("Test Channel").build();
        entityManager.persistAndFlush(channel);

        assertThat(channel.getSlug()).isEqualTo("test-channel");
    }

    private Channel persistChannel(String slug, String name) {
        Channel channel = Channel.builder()
                .slug(slug)
                .name(name)
                .description(name + " discussions")
                .build();
        return entityManager.persistAndFlush(channel);
    }
}
